[[Оператор with]] может работать только с объектами, которые реализуют протокол контекстного менеджера.

Приведенный ниже код:

```python
class Cat:
    def __init__(self, name):
        self.name = name


with Cat('Кемаль') as cat:
    print(cat)
```

приводит к возбуждению исключения:

```no-highlight
AttributeError: __enter__
```

поскольку класс `Cat` не реализует протокол контекстного менеджера.

   В Python 3.11 возбуждается исключение `TypeError: 'Cat' object does not support the context manager protocol`.

Контекстный менеджер — это объект, определяющий контекст выполнения в операторе `with`.

Протокол контекстных менеджеров состоит всего из двух методов:

- [[Магический метод __enter__()]] – вводит контекст и при необходимости возвращает некоторый объект. Значение, возвращаемое этим методом, привязывается к переменной в предложении `as` оператора `with`
- [[Магический метод __exit__()]] – предоставляет выход из контекста и возвращает логический флаг (тип `bool`), указывающий на то, следует ли подавлять возбужденное исключение. При возбуждении исключения во время выполнения тела блока `with`, аргументы содержат тип исключения `exc_type`, объект исключения `exc_value` и информацию о трассировке `traceback`. В противном случае все три аргумента равны `None`

Создадим простой контекстный менеджер `CustomContextManager`, который просто выводит текст в методах `__enter__()` и `__exit__()`:

```python
class CustomContextManager:
    def __enter__(self):
        print('Вход в контекстный менеджер...')
        return 'Python generation!'

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')
        print(exc_type, exc_value, traceback, sep='\n')
```

Приведенный ниже код:

```python
with CustomContextManager() as manager:
    print(manager)
```

выводит:

```no-highlight
Вход в контекстный менеджер...
Python generation!
Выход из контекстного менеджера...
None
None
None
```

При выполнении оператора `with` сначала создается экземпляр класса `CustomContextManager`, а затем вызывается его метод `__enter__()`, который печатает текст `Вход в контекстный менеджер...` и возвращает строку `Python generation!`, которая присваивается переменной `manager`. Далее исполняется тело оператора `with`, после чего вызывается метод `__exit__()`. Поскольку во время выполнения тела оператора `with` не было возбуждено никакое исключение, то все три аргумента `exc_type, exc_value` и `traceback` метода `__exit__()` равны `None`.

Рассмотрим ситуацию, в которой в теле оператора `with` возбуждается исключение.

Приведенный ниже код:

```python
with CustomContextManager() as manager:
    print(manager)
    print(manager[100])                                 # обращаемся по несуществующему индексу
```

выводит (адрес может отличаться):

```no-highlight
Вход в контекстный менеджер...
Python generation!
Выход из контекстного менеджера...
<class 'IndexError'>
string index out of range
<traceback object at 0x000001E5CBB57500>
```

после чего возбуждается исключение:

```no-highlight
IndexError: string index out of range
```

Как мы видим, аргументы метода `__exit__()` содержат информацию о возбужденном исключении:

- `exc_type` – тип исключения, в данном случае `IndexError`
- `exc_value` – объект самого исключения
- `traceback` – информация о трассировке

)В атрибуте `exc_value.args` можно найти параметры, переданные конструктору исключения, например, сообщение об  
ошибке.

## Обработка исключений внутри блока with

Для обработки исключений внутри блока `with` нужно добавить дополнительный код в метод `__exit__()`. Как уже было сказано выше, метод `__exit__()` возвращает логический флаг (тип `bool`), указывающий на то, следует ли подавлять возбужденное исключение или нет.

Модифицируем наш контекстный менеджер `CustomContextManager` следующим образом:

```python
class CustomContextManager:
    def __enter__(self):
        print('Вход в контекстный менеджер...')
        return 'Python generation!'

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')
        if isinstance(exc_value, IndexError):
            print(f'Тип возникшего исключения: {exc_type}')
            print(f'Текст исключения: {exc_value}')
            return True                                 # подавляем возбужденное исключение IndexError
```

Приведенный ниже код:

```python
with CustomContextManager() as manager:
    print(manager)
    print(manager[100])                                 # обращаемся по несуществующему индексу
```

выводит:

```no-highlight
Вход в контекстный менеджер...
Python generation!
Выход из контекстного менеджера...
Тип возникшего исключения: <class 'IndexError'>
Текст исключения: string index out of range
```

и больше не приводит к возбуждению исключения `IndexError`, поскольку мы обработали этот тип исключения в методе `__exit__()`. Возврат значения `True` позволяет поглотить возбужденное в теле оператора `with` исключение и продолжить выполнение с оператора, **непосредственно следующего** за оператором `with`.

Если при выполнении тела оператора `with` не возбуждается исключение `IndexError`, то метод возвращает значение `None`, которое приводится к логическому `False`. Для придания наглядности рекомендуется явно возвращать значение `False` из метода `__exit__()`:

```python
class CustomContextManager:
    def __enter__(self):
        print('Вход в контекстный менеджер...')
        return 'Python generation!'

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')
        if isinstance(exc_value, IndexError):
            print(f'Тип возникшего исключения: {exc_type}')
            print(f'Текст исключения: {exc_value}')
            return True                                 # подавляем возбужденное исключение IndexError
        return False                                    # все остальные типы исключений не подавляются
```

Передаваемое исключение `exc_value` не следует никогда повторно возбуждать в методе `__exit__()`, вместо этого метод `__exit__()` должен возвращать значение `False`, чтобы указать, что метод завершился успешно и не хочет подавлять возбужденное исключение. Это позволяет коду управления контекстом легко определять, действительно ли метод `__exit__()` потерпел неудачу.

Исключения, возникающие во время выполнения метода `__exit__()`, заменяют все исключения, возникшие в теле оператора `with`.

## Примеры использования встроенных контекстных менеджеров

**Пример 1.** Самым простым вариантом использования встроенного контекстного менеджера является файловый объект, который возвращает функция `open()`. Этот объект реализует протокол контекстного менеджера, в чем несложно убедиться.

Приведенный ниже код:

```python
with open('output.txt', mode='w', encoding='utf-8') as file:
    print('__enter__' in dir(file))                      # наличие метода __enter__()
    print('__exit__' in dir(file))                       # наличие метода __exit__()
    file.write('Python generation!')
```

создает текстовый файл с именем `output.txt` с содержимым `Python generation!` и выводит:

```no-highlight
True
True
```

**Пример 2.** Мы можем использовать контекстный менеджер для настройки объектов типа `Decimal`, который обеспечивает точные вычисления с вещественными числами (в отличие от типа `float`). Функция `localcontext()` модуля `decimal` позволяет настраивать активный контекст для арифметических операций. С помощью данного контекста мы можем устанавливать точность, правила округления и т.д.

Приведенный ниже код:

```python
from decimal import Decimal, localcontext

num1 = Decimal('1')
num2 = Decimal('9')

print(num1 / num2)                   # по умолчанию 28 знаков после запятой

with localcontext() as ctx:
    ctx.prec = 5                     # устанавливаем 5 знаков после запятой
    print(num1 / num2)

with localcontext() as ctx:
    ctx.prec = 10                    # устанавливаем 10 знаков после запятой
    print(num1 / num2)
```

выводит:

```no-highlight
0.1111111111111111111111111111
0.11111
0.1111111111
```



**Пример 3.** Встроенный модуль `os` содержит функцию `scandir()`, которая возвращает итератор типа `ScandirIterator`, поддерживающий протокол контекстного менеджера. Эта функция специально разработана для обеспечения оптимальной производительности при перемещении по структуре папок.

Приведенный ниже код:

```python
import os

with os.scandir('.') as entries:
    for entry in entries:
        print(entry.name, '--->', entry.stat().st_size, 'bytes')
```

выводит информацию о файлах, которые находятся в папке с исполняющимся файлом (вывод может отличаться):

```no-highlight
18+.png ---> 60 bytes
ducks.zip ---> 641592 bytes
logo.bmp ---> 32160 bytes
with.py ---> 138 bytes
Любимая уточка Бэтмен.txt ---> 97 bytes
Математика для программиста.doc ---> 759780 bytes
Мемуары Поколения.txt ---> 5909400 bytes
План для курса алгоритмы и структуры данных.txt ---> 590940 bytes
```



**Пример 4.** Встроенный модуль `tempfile` (подробнее по [ссылке](https://docs.python.org/3/library/tempfile.html)) содержит контекстный менеджер `TemporaryFile`, который позволяет создавать и удалять временные файлы автоматически.

Приведенный ниже код:

```python
from tempfile import TemporaryFile

with TemporaryFile(mode='r+') as file:
    file.write('Python generation!')
    file.seek(0)
    content = file.read()
    print(content)
```

выводит:

```no-highlight
Python generation!
```

В этом примере временный файл создается при входе в тело блока контекста и удаляется при выходе. Такой подход позволяет избежать утечек памяти и ошибок, связанных с неправильным удалением временных файлов.



**Пример 5.** Встроенный модуль `threading` содержит контекстный менеджер `Lock`, который обеспечивает примитивную блокировку для предотвращения одновременного изменения общего ресурса несколькими потоками в многопоточном приложении.

Приведенный ниже код:

```python
from threading import Lock


with Lock() as lock:
    # защищенная область
    # смело выполняем любые действия, не думая о гонке потоков
```

создает защищенную область критическая секция, которая предотвращает одновременный доступ из разных потоков к общим ресурсам.



 Приведенный ниже код: 

```python
with EXPRESSION as TARGET:
    SUITE


manager = (EXPRESSION)                                  
# переменная manager ссылается на значение EXPRESSION (обычно это экземпляр какого-либо класса)

enter = type(manager).__enter__                         
# переменная enter ссылается на метод __enter__() класса, к которому относится manager

exit = type(manager).__exit__                           
# переменная exit ссылается на метод __exit__() класса, к которому относится manager

value = enter(manager)                                  
# переменной value присваивается значение, возвращаемое методом __enter__().
# Для правильной отработки метода ему передается экземпляр manager (self)

hit_except = False                                      
# переменной hit_except присваивается значение False. Это сыграет роль в отлавливании исключений.

try:
    TARGET = value                                      
# переменной TARGET присваиваем значение value. Это то значение, которое возвращается методом __enter__()

    SUITE                                               
# SUITE — это блок кода внутри контекста with, пробуем его выполнить

except:
    hit_except = True                                   
# если SUITE выбросил исключение, попадаем сюда и присваиваем переменной hit_except значение True

    if not exit(manager, *sys.exc_info()):              
# в метод __exit__() передаем экземпляр manager и информацию об исключении (тип, объект, трассировка).
# информацию о типе, объекте и трассировке возвращает функция sys.exc_info()
 
        raise                                           
# если метод __exit__() вернул True, ничего не происходит, если False, возбуждается исключение

finally:
    if not hit_except:                                  
# блок finally выполняется в любом случае.
# Если было исключение, переменная hit_except имеет значение True и условие не выполняется

        exit(manager, None, None, None)                 
# если исключения не было,  переменная hit_except имеет значение False, условие выполняется 
# и метод __exit__() завершается штатно

равнозначен коду:

```python
manager = (EXPRESSION)
enter = type(manager).__enter__
exit = type(manager).__exit__
value = enter(manager)
hit_except = False

try:
    TARGET = value
    SUITE
except:
    hit_except = True
    if not exit(manager, *sys.exc_info()):
        raise
finally:
    if not hit_except:
        exit(manager, None, None, None)
```

![](https://ucarecdn.com/f40928bd-11f4-42e0-b8ab-02ef78f0e43c/)

При использовании оператора `with` часто забывают создать сам объект контекстного менеджера, пропуская скобки `()`.

Для контекстного менеджера:

```python
class CustomContextManager:
    def __enter__(self):
        print('Вход в контекстный менеджер...')

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')
```

правильным использованием является:

```python
with CustomContextManager() as manager:
    print(manager)
```

В то время как приведенный ниже код:

```python
with CustomContextManager as manager:
    print(manager)
```

приводит к возбуждению исключения:

```no-highlight
AttributeError: __enter__
```

 Менеджеры контекста – это обычные классы, которые могут содержать дополнительные атрибуты и методы, включая магические методы.

Приведенный ниже код:

```python
class CustomContextManager:
    def __init__(self, value):
        self.value = value

    def __enter__(self):
        print('Вход в контекстный менеджер...')
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')

    def __repr__(self):
        return f'CustomContextManager(value={repr(self.value)})' 


with CustomContextManager('pygen') as manager:
    print(manager)
    print(manager.value)
```

выводит:

```no-highlight
Вход в контекстный менеджер...
CustomContextManager(value='pygen')
pygen
Выход из контекстного менеджера...
```

Метод `__enter__()` часто возвращает ссылку на сам объект контекстного менеджера (`self`), однако это не обязательно, то есть метод `__enter__()` может возвращать любой объект, включая `None`. При этом стоит отметить тонкий, но важный момент: объект контекстного менеджера – это результат вычисления выражения после слова `with`, но значение, связанное с переменной в части `as`, – результат вызова метода `__enter__()` объекта контекстного менеджера.

**Примечание 5.** Для того чтобы передать значения из метода `__enter__()` в тело блока контекста `with`, нужно использовать атрибуты объекта, возвращаемого методом `__enter__()`.

Приведенный ниже код:

```python
class CustomContextManager:
    def __init__(self, value):
        self.value = value

    def __enter__(self):
        print('Вход в контекстный менеджер...')
        self.name = 'Кемаль'
        self.breed = 'Британский'
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')


with CustomContextManager('pygen') as manager:
    print(manager.value)
    print(manager.name)
    print(manager.breed)
```

выводит:

```no-highlight
Вход в контекстный менеджер...
pygen
Кемаль
Британский
Выход из контекстного менеджера...
```

 Приведенный ниже код:

```
with A() as a, B() as b:
    SUITE
```

равнозначен коду:

```
with A() as a:
    with B() as b:
        SUITE
```

который, в свою очередь, равнозначен коду:

```
with (
    A() as a,
    B() as b,
):
    SUITE
```


С помощью контекстных менеджеров мы можем не только грамотно управлять ресурсами, но и выполнять любую пару операций, которую необходимо выполнить до и после каких-то действий. Например:

- открытие и закрытие
- создание и удаление
- изменение данных и возврат к начальным данным
- блокировка и освобождение
- вход и выход
- старт и стоп
- и т.д.

Приведем несколько примеров реализации контекстных менеджеров.

**Пример 1.** Контекстный менеджер `Trace` выводит информацию перед входом в блок `with` и после выхода из блока `with`, включая информацию об исключении, если оно было возбуждено во время выполнения блока `with`.

```python
class Trace:
    def __enter__(self):
        print('Начало выполнения блока with')

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_value:
            print(f'Во время выполнения блока with было возбуждено исключение {exc_value}')
        print('Конец выполнения блока with')
        return True                           # обрабатываем все типы исключений
```

Приведенный ниже код:

```python
with Trace():
    print('Python generation!')
```

выводит:

```no-highlight
Начало выполнения блока with
Python generation!
Конец выполнения блока with
```

Приведенный ниже код:

```python
with Trace():
    print('Python generation!')
    print(1 / 0)
```

выводит: 

```no-highlight
Начало выполнения блока with
Python generation!
Во время выполнения блока with было возбуждено исключение division by zero
Конец выполнения блока with
```

Обратите внимание, что метод `__exit__()` возвращает значение `True`, таким образом любое возбужденное в блоке `with` исключение будет обработано.

**Пример 2.** Контекстный менеджер `WritableTextFile` позволяет работать с открытыми для записи текстовыми файлами в кодировке `UTF-8`:

```python
class WritableTextFile:
    def __init__(self, path):
        self.path = path

    def __enter__(self):
        self.file = open(self.path, mode='w', encoding='utf-8')
        return self.file

    def __exit__(self, exc_type, exc_value, traceback):
        if self.file:
            self.file.close()
```

Приведенный ниже код:

```python
with WritableTextFile('output.txt') as file:
    file.write('Python generation!')
```

создает текстовый файл `output.txt` в кодировке `UTF-8` с содержимым `Python generation!`.

Обратите внимание, что метод `__enter__()` возвращает файловый объект, в который производится запись данных. Иногда при написании контекстных менеджеров у нас не бывает подходящего объекта, который можно вернуть из метода `__enter__()`. В этих случаях мы можем вернуть `None` явно или просто положиться на неявное возвращаемое значение, которое также равно `None`.

**Пример 3.** Контекстный менеджер `RedirectedStdout` **временно** перенаправляет стандартный вывод `sys.stdout` на некоторый файл на диске:

```python
import sys

class RedirectedStdout:
    def __init__(self, new_output):
        self.new_output = new_output

    def __enter__(self):
        self.standard_output = sys.stdout
        sys.stdout = self.new_output

    def __exit__(self, exc_type, exc_value, traceback):
        sys.stdout = self.standard_output 
```

Приведенный ниже код:

```python
with open('output.txt', mode='w', encoding='utf-8') as file:
    with RedirectedStdout(file):
        print('Python generation!')
    print('Возврат к стандартному потоку вывода')
```

создает текстовый файл `output.txt` в кодировке `UTF-8` с содержимым `Python generation!`, а также выводит текст `Возврат к стандартному потоку вывода`.

Класс `RedirectedStdout` — это хороший пример контекстного менеджера, у которого нет полезного значения для возврата из метода `__enter__()`.

**Пример 4.** Контекстный менеджер `Timer` позволяет измерять время выполнения блока кода:

```python
from time import perf_counter

class Timer:
    def __enter__(self):
        self.start = perf_counter()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.elapsed = perf_counter() - self.start
```

Приведенный ниже код:

```python
from time import sleep

with Timer() as timer:
    sleep(0.7)
    sleep(1.5)
print('Затраченное время:', timer.elapsed)
```

выводит (время может отличаться):

```no-highlight
Затраченное время: 2.208050799788907
```

Мы можем немного модифицировать контекстный менеджер `Timer`, чтобы метод `__enter__()` возвращал не `self`, а функцию, которая возвращает вычисленное значение.

```python
from time import perf_counter

class Timer:
    def __enter__(self):
        self.start = perf_counter()
        self.end = 0.0
        return lambda: self.end - self.start

    def __exit__(self, exc_type, exc_value, traceback):
        self.end = perf_counter()
```

Приведенный ниже код:

```python
from time import sleep

with Timer() as timer:
    sleep(0.7)
    sleep(1.5)
print('Затраченное время:', timer())
```

выводит (время может отличаться):

```no-highlight
Затраченное время: 2.206870499998331
```